import type { Metadata } from "next";
import { Inter } from "next/font/google"; // ✅ Import Inter and keep Geist_Mono
import "../globals.css";
import Nav from "@/layouts/Nav";
import { JobProvider } from "@/context/Job";

// ✅ Instantiate Inter font (replacing Geist)
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Promolink",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <JobProvider>
        <body
          className={`${inter.variable} antialiased bg-[#EBF2FA]`} //  Apply Inter and Geist_Mono
        >
          {/* <Nav /> */}

          {children}
        </body>
      </JobProvider>
    </html>
  );
}
