import type { Metadata } from "next";
import { Inter } from "next/font/google"; // ✅ Import Inter and keep Geist_Mono
import "../globals.css";
import Nav from "@/layouts/Nav";

// ✅ Instantiate Inter font (replacing Geist)
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Promolink",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased bg-[#f6f6f8]`} //  Apply Inter and Geist_Mono
      >
        <Nav />

        {children}
      </body>
    </html>
  );
}
